export const API_LIST = Object.freeze({
  BASE_URL: import.meta.env.VITE_BASE_URL,
  LOGIN: import.meta.env.VITE_LOGIN,
  REGISTER: import.meta.env.VITE_REGISTER,
  HISTORY: import.meta.env.VITE_HISTORY,
  STATS: import.meta.env.VITE_STATS,
  REVIEW_ARTICLE: import.meta.env.VITE_REVIEW,
  SUBMIT_ARTICLE: import.meta.env.VITE_SUBMIT,
  DRAFT_ARTICLE: import.meta.env.VITE_DRAFT,
  DRAFT_BY_ARTICLE: import.meta.env.VITE_DRAFT_BY_ID,
  REVERTED_POST: import.meta.env.VITE_REVERTED_POST,
  GET_ARTICLE: import.meta.env.VITE_GET_ARTICLE,
  DELETE_ARTICLE: import.meta.env.VITE_DELETE_ARTICLE,
  EDITOR_REVIEW_ARTICLE: import.meta.env.VITE_EDITOR_ARTICLE_REVIEW,
  EDITOR_STATS: import.meta.env.VITE_EDITOR_STATS,
  PUBLISH_CENTER: import.meta.env.VITE_PUBLISH_CENTER,
  SCHEDULED_POST: import.meta.env.VITE_SCHEDULE_POST,
  CALENDAR_EVENTS: import.meta.env.VITE_CALENDAR_DATA,
  CANCEL_SCHEDULED_POST: import.meta.env.VITE_CANCEL_SCHEDULED_POST,
});
